version: '3.8'

services:
  backend:
    build: .
    container_name: proyecto-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sistemaBdd
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kamila
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: proyecto-db
    restart: always
    environment:
      POSTGRES_DB: sistemaBdd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kamila
    ports:
      - "5432:5432"
    volumes:
      # 1. Persistencia de datos
      - pgdata:/var/lib/postgresql/data
      # 2. Scripts de inicialización
      - ./bd:/docker-entrypoint-initdb.d

volumes:
  pgdata:
